### PR TITLE
Update DC to 3.0.1

### PR DESCRIPTION
**Pull request by ktham**
There are a few fixes we need from the 2.1.1 release of DependencyCheck.
Would appreciate if you can cut a release at your earliest convenience. Thanks!

### CODE REVIEW

**Comment by albuch** [comment]
@ktham thank you for the PR. It seems that there were new vulnerabilities introduced in the latest dependency-check-core release which need to be checked for false positives and reported to the upstream project.
I'll have a look at it the next couple of days.

**Comment by ktham** [comment]
@albuch Thank you!

**Comment by albuch** [comment]
After some investigation it seems all of the reported CVEs are false positives. We could add a suppression file to the project until/if the underlying issue in DC is fixed.
If you need a release rather urgently you can add the suppression file to the PR.

**Comment by albuch** [comment]
Thanks @ktham for updating tee pull request. I'll check the build and the PR this weekend to cut a release soon.

**Comment by ktham** [comment]
@albuch Great, thank you!

**Pull request merged**
